spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.example.com
    port: 587
    username: ruafyseyidov@gmail.com
    password: ausb enca syiw biyi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: your_secret_key
  expirationMs: 3600000
