spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ruafyseyidov@gmail.com
    password: ausb enca syiw biyi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true